#!/usr/bin/env python
"""Debug the _norm function"""
import unicodedata

def _norm(s):
    s = str(s).strip()
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = s.upper()
    s = ''.join(c for c in s if c.isalnum() or c == ' ')
    s = s.strip()
    s = '_'.join(s.split())
    return s

tests = [
    "Fecha de Nacimiento",
    "FECHA_DE_NACIMIENTO",
    "No",
    "CONSECUTIVO",
    "No. De Identificación",
    "NO_DE_IDENTIFICACION",
    "Tipo de documento de identidad",
    "TIPO_DE_DOCUMENTO_DE_IDENTIDAD",
    "Regimen Afiliacion",
    "REGIMEN_DE_AFILIACION",
    "Pertenecia Etnica",
    "PERTENECIA_ETNICA",
    "Departamento Residencia",
    "DEPARTAMENTO_DE_RESIDENCIA",
    "Municipio de Residencia",
    "MUNICIPIO_DE_RESIDENCIA",
    "Nombre de la IPS Primaria",
    "NOMBRE_DE_LA_IPS_PRIMARIA",
    "Fecha de Ingreso al Control Prenatal",
    "FECHA_DE_INGRESO_AL_CONTROL_PRENATAL",
    "Hipertension arterial",
    "HIPERTENSION_ARTERIAL",
    "Grupo Poblacional",
    "GRUPO_POBLACIONAL",
    "Estado Civil",
    "ESTADO_CIVIL",
    "Nivel Educativo",
    "NIVEL_EDUCATIVO",
    "Mujer cabeza de Hogar",
    "MUJER_CABEZA_DE_HOGAR",
    "Control Tradicional",
    "CONTROL_TRADICIONAL",
    "Gestante Renuente",
    "GESTANTE_RENUENTE",
    "Otras condiciones medicas graves",
    "OTRAS_CONDICIONES_MEDICAS_GRAVES",
    "Periodo Intergenésico",
    "PERIODO_INTERGENESICO",
    "Peso Inicial (kg)",
    "PESO_INICIAL_KG",
    "Talla (metros)",
    "TALLA_METROS",
    "Antecedentes de eventos obstétricos\ndesfavorables",
    "ANTECEDENTES_DE_EVENTOS_OBSTETRICOS_DESFAVORABLES",
    "Teléfono usuaria",
    "TELEFONO_USUARIA",
    "Clasificación del riesgo obstetrico",
    "CLASIFICACION_DEL_RIESGO",
    "Causas de Alto Riesgo obstetrico",
    "CAUSAS_DE_ALTO_RIESGO",
    "Asesoria Prueba VIH",
    "ASESORIA_PRUEBA_VIH",
    "Fecha de Diagnostico del embarazo",
    "FECHA_DE_DIAGNOSTICO_DEL_EMBARAZO",
    "Fecha toma Segunda Prueba VIH",
    "TOMA_SEGUNDA_PRUEBA_VIH",
    "Resultado Primer Tamizaje prueba de VIH",
    "RESULTADO_PRIMER_TAMIZAJE",
    "Resultado Segundo Tamizaje Prueba de VIH",
    "RESULTADO_SEGUNDO_TAMIZAJE",
    "Resultado Tercer Tamizaje Prueba de VIH",
    "RESULTADO_TERCER_TAMIZAJE",
    "Fecha Primera Prueba Treponemica Rapida Sifilis",
    "FECHA_PRIMERA_PRUEBA_TREPONEMICA_RAPIDA_SIFILIS",
    "Resultado Primera Prueba Treponemica Rapida Sifilis",
    "RESULTADO_PRIMERA_PRUEBA_TREPONEMICA_RAPIDA_SIFILIS",
    "Fecha Segunda Prueba Treponemica Rapida Sifilis",
    "FECHA_SEGUNDA_PRUEBA_TREPONEMICA_RAPIDA_SIFILIS",
    "Resultado Segunda Prueba Treponemica Rapida Sifilis",
    "RESULTADO_SEGUNDA_PRUEBA_TREPONEMICA_RAPIDA_SIFILIS",
    "Fecha Tercera Prueba Treponemica Rapida Sifilis",
    "FECHA_TERCERA_PRUEBA_TREPONEMICA_RAPIDA_SIFILIS",
    "Resultado Tercera Prueba Treponemica Rapida Sifilis",
    "RESULTADO_TERCERA_PRUEBA_TREPONEMICA_RAPIDA_SIFILIS",
    "Fecha prueba confirmatoria Según Algoritmo",
    "PRUEBA_CONFIRMATORIA_SEGUN_ALGORITMO",
    "Fecha de diagnóstico de sífilis",
    "FECHA_DE_DIAGNOSTICO_DE_SIFILIS",
    "Tratamiento instaurado",
    "TRATAMIENTO_INSTAURADO",
    "Fecha de inicio del tratamiento",
    "FECHA_DE_INICIO_DEL_TRATAMIENTO",
    "Fecha de segunda dosis del tratamiento",
    "FECHA_DE_SEGUNDA_DOSIS_DEL_TRATAMIENTO",
    "Fecha de tercera dosis del tratamiento",
    "FECHA_DE_TERCERA_DOSIS_DEL_TRATAMIENTO",
    "Fecha de Toma de Urocultivo",
    "FECHA_DE_TOMA_DE_UROCULTIVO_Y_ANTIBIOGRAMA",
    "Resultado Urocultivo",
    "RESULTADO_UROCULTIVO",
    "Fecha Toma Glicemia",
    "FECHA_TOMA_GLICEMIA",
    "Resultado Glicemia",
    "RESULTADO_GLICEMIA",
    "Fecha Prueba de Tolerancia Oral Glucosa",
    "FECHA_REALIZACION_PRUEBA_TOLERANCIA_ORAL_GLUCOSA",
    "Resultado Prueba de Tolerancia Oral Glucosa",
    "RESULTADO_PRUEBA_DE_TOLERANCIA_ORAL_GLUCOSA",
    "Fecha 1ra Realizacion Hemoglobina",
    "FECHA_REALIZACION_HEMOGRAMA_INICIAL",
    "Resultado 1ra Hemoglobina",
    "RESULTADO_1RA_HEMOGLOBINA",
    "Fecha 2da Realizacion Hemoglobina",
    "FECHA_REALIZACION_SEGUNDO_HEMOGRAMA_SEMANA_28",
    "Resultado 2da Hemoglobina",
    "RESULTADO_2DA_HEMOGLOBINA",
    "Fecha 3ra Realizacion Hemoglobina",
    "RESULTADO_3RA_HEMOGLOBINA",
    "Resultado Realizacion Hemoclasificación (Factor RH)",
    "FECHA_REALIZACION_HEMOCLASIFICACION",
    "Fecha de Antigeno Superficie Hepatitis B",
    "FECHA_DE_LA_REALIZACION_ANTIGENO_SUPERFICIE_HEPATITIS_B",
    "Resultado Antigeno Superficie Hepatitis B",
    "RESULTADO_ANTIGENO_SUPERFICIE_HEPATITIS_B",
    "Fecha Tamizaje Toxoplasma",
    "FECHA_TAMIZAJE_TOXOPLASMA",
    "Resultado Toxoplasma",
    "RESULTADO_TOXOPLASMA",
    "Fecha Citologia Cervicouterina",
    "FECHA_DE_TAMIZAJE_PARA_CA_CUELLO_UTERINO",
    "Resultado Tamizaje de cuello uterino",
    "RESULTADO_TAMIZAJE_DE_CUELLO_UTERINO",
    "Fecha de la prueba de Rubeola",
    "FECHA_DE_LA_REALIZACION_PRUEBA_IGG_RUBEOLA",
    "Resultado Rubeola",
    "RESULTADO_RUBEOLA",
    "Fecha Prueba de Tamizaje para Estreptococo Grupo B",
    "FECHA_REALIZACION_PRUEBA_TAMIZAJE_ESTREPTOCOCO_GRUPO_B",
    "Resultado Prueba de Tamizaje para Estreptococo Grupo B",
    "RESULTADO_PRUEBA_DE_TAMIZAJE_PARA_ESTREPTOCOCO_GRUPO_B",
    "Fecha Toma de Gota Gruesa (Malaria)",
    "FECHA_TOMA_DE_GOTA_GRUESA_MALARIA",
    "Resultado Gota gruesa (Malaria)",
    "RESULTADO_GOTA_GRUESA_MALARIA",
    "Fecha de Realización Tamizaje Chagas",
    "FECHA_DE_REALIZACION_TAMIZAJE_CHAGAS",
    "Resultado Chagas",
    "RESULTADO_CHAGAS",
    "FECHA DE APLICACIÓN INFLUENZA (Desde Semana 14)",
    "FECHA_DE_APLICACION_INFLUENZA_DESDE_SEMANA_14",
    "FECHA DE APLICACIÓN TOXOIDE Según Antecedente Vacunal",
    "FECHA_DE_APLICACION_TOXOIDE_SEGUN_ANTECEDENTE_VACUNAL",
    "FECHA DE APLICACIÓN DPT ACELULAR (Semana 26)",
    "FECHA_DE_APLICACION_DPT_ACELULAR_SEMANA_26",
    "FECHA DE APLICACIÓN COVID-19 (1 En la Gestación)",
    "FECHA_DE_APLICACION_COVID19_1_EN_LA_GESTACION",
    "FECHA DE APLICACIÓN VSR (Semana 28 - 36)",
    "FECHA_DE_APLICACION_VSR_SEMANA_28_36",
    "FECHA CONSULTA ODONTOLOGICA",
    "FECHA_CONSULTA_ODONTOLOGICA",
    "Ecografia obstétrica con translucencia nucal (10,6 - 13,6)",
    "PRIMERA_ECOGRAFIA_OBSTETRICA_10_13",
    "Ecografia Obstetrica para la detección de anomalias estructurales (18 - 23)",
    "ECOGRAFIA_OBSTETRICA_PARA_LA_DETECCION_DE_ANOMALIAS_ESTRUCTURALES_18_23",
    "Otras ecografías?",
    "OTRAS_ECOGRAFIAS",
    "Fecha suministro Acido Folico",
    "FECHA_SUMINISTRO_ACIDO_FOLICO",
    "Fecha suministro Calcio (Semana 14)",
    "FECHA_SUMINISTRO_CALCIO_SEMANA_14",
    "Fecha suministro Hierro",
    "FECHA_SUMINISTRO_HIERRO",
    "Tipo de tratamiento suminitrado para anemia",
    "TIPO_DE_TRATAMIENTO_SUMINITRADO_PARA_ANEMIA",
    "Relación entre Anemia vs tratamiento",
    "RELACION_ENTRE_ANEMIA_VS_TRATAMIENTO",
    "Condicion del suministro del ASA",
    "CONDICION_DEL_SUMINISTRO_DEL_ASA",
    "fecha de suministro",
    "FECHA_DE_SUMINISTRO_DE_TRATAMIENTO",
    "Fecha Desparasitación Antihelmintica II y III Trimestre (Albendazo 400 Mg Dosis Unica)",
    "FECHA_DESPARASITACION_ANTIHELMINTICA_II_Y_III_TRIMESTRE_ALBENDAZO_400_MG_DOSIS_UNICA",
    "Fecha 1er Control",
    "FECHA_1ER_CONTROL",
    "Quien Realizó el Control",
    "QUIEN_REALIZO_EL_CONTROL",
    "peso actual",
    "PESO",
    "talla actual",
    "TALLA_METROS",
    "TA ACTUAL",
    "TA_ACTUAL",
    "ALTURA UTERINA",
    "ALTURA_UTERINA",
    "FCF",
    "FCF",
    "Fecha Primera Consulta Ginecología",
    "FECHA_PRIMERA_CONSULTA_GINECOLOGIA",
    "Fecha Segunda Consulta Ginecología",
    "FECHA_SEGUNDA_CONSULTA_GINECOLOGIA",
    "Fecha Tercera Consulta Ginecología",
    "FECHA_TERCERA_CONSULTA_GINECOLOGIA",
    "Fecha Consulta Nutrición",
    "FECHA_CONSULTA_NUTRICION",
    "Fecha Consulta Psicología",
    "FECHA_CONSULTA_PSICOLOGIA",
    "Fecha de Atención Otro Especialista",
    "FECHA_DE_ATENCION_OTRO_ESPECIALISTA",
    "Quien Realizó la Consulta",
    "QUIEN_REALIZO_LA_CONSULTA",
    "Fecha de aborto",
    "FECHA_DE_ABORTO",
    "Semanas de Gestación",
    "SEMANAS_DE_GESTACION",
    "Fecha de Parto",
    "FECHA_DE_PARTO",
    "Caracteristicas del parto",
    "CARACTERISTICAS_DEL_PARTO",
    "Parto atendido por",
    "PARTO_ATENDIDO_POR",
    "No. Semanas de gestación",
    "NO_SEMANAS_DE_GESTACION",
    "Multiplicidad del embarazo",
    "MULTIPLICIDAD_DEL_EMBARAZO",
    "Complicaciones durante el parto",
    "COMPLICACIONES_DURANTE_EL_PARTO",
    "Tipo Complicación",
    "TIPO_COMPLICACION",
    "UCI Materna",
    "UCI_MATERNA",
    "Toma de pruebas ITS intraparto",
    "TOMA_DE_PRUEBAS_ITS_INTRAPARTO",
    "Resultado POSITIVO",
    "RESULTADO_POSITIVO",
    "Fecha",
    "FECHA_DE_NACIMIENTO",
    "Causa de la defunción",
    "CAUSA_DE_LA_DEFUNCION",
    "RENUENTE A PLANIFICACION FAMILIAR",
    "RENUENTE_A_PLANIFICACION_FAMILIAR",
    "OBSERVACIONES GENERALES",
    "OBSERVACIONES_GESTION_RIESGO",
    "Solicita ive IVE?",
    "SE_IDENTIFICAN_CAUSALES_PARA_IVE",
    "Clacificacion del riesgo de preeclampsia",
    "CLASIFICACION_DEL_RIESGO",
    "Causas de Alto Riesgo de preeclampsia",
    "CAUSAS_DE_ALTO_RIESGO",
    "Clacificacion del riesgo tromboembolico",
    "CLASIFICACION_DEL_RIESGO",
    "Causas de Alto Riesgo tromboembolico",
    "CAUSAS_DE_ALTO_RIESGO",
    "fecha de suministro de tratamiento",
    "FECHA_DE_SUMINISTRO_DE_TRATAMIENTO",
    "tratamiento Instaurado",
    "TRATAMIENTO_INSTAURADO",
    "Remitida a especialista?",
    "REMITIDA_A_ESPECIALISTA",
    "Describa cual(es) especialistas la han atendido",
    "DESCRIBA_CUAL_ES_ESPECIALISTAS_LA_HAN_ATENDIDO",
    "Clasificación del riesgo obstetrico",
    "CLASIFICACION_DEL_RIESGO",
    "Causas de Alto Riesgo obstetrico",
    "CAUSAS_DE_ALTO_RIESGO",
    "Si la respuesta anterior es  SI describa la otra condición médica grave",
    "SI_LA_RESPUESTA_ANTERIOR_ES_SI_DESCRIBA_LA_OTRA_CONDICION_MEDICA_GRAVE",
]

for i in range(0, len(tests), 2):
    csv_name = tests[i]
    db_col = tests[i+1]
    csv_norm = _norm(csv_name)
    db_norm = _norm(db_col)
    match = "MATCH" if csv_norm == db_norm else "MISMATCH"
    print(f"  [{match:8s}] CSV={csv_name!r:55s} -> {csv_norm!r:55s} DB={db_col!r:55s} -> {db_norm!r}")
