def field(name: str, type_: str, required: bool = True, allowed: list[str] | None = None):
    return {"name": name, "type": type_, "required": required, "allowed": allowed or []}

SI_NO = ["SI", "NO"]
SI_NO_SD = ["SI", "NO", "SIN DATO"]

RAW_FIELDS = [
    # ── Datos básicos (1-20) ──
    ("TIPO DE DOCUMENTO DE IDENTIDAD", "SET"),
    ("NO. DE IDENTIFICACION", "INT"),
    ("PRIMER APELLIDO", "TEXT"),
    ("SEGUNDO APELLIDO", "TEXT"),
    ("PRIMER NOMBRE", "TEXT"),
    ("SEGUNDO NOMBRE", "TEXT"),
    ("FECHA DE NACIMIENTO", "TEXT"),
    ("EDAD(AÑOS)", "INT"),
    ("GENERO", "SET"),
    ("DEPARTAMENTO", "TEXT"),
    ("MUNICIPIO", "INT"),
    ("ZONA AFILIACION", "SET"),
    ("REGIMEN DE AFILIACION", "SET"),
    ("IPS PRIMARIA", "TEXT"),
    ("NIT IPS PRIMARIA", "INT"),
    ("RESGUARDO", "TEXT"),
    ("TELEFONO", "INT"),
    ("DIRECCION", "TEXT"),
    ("ETNIA", "SET"),
    ("ASENTAMIENTO", "TEXT"),

    # ── Citología 1 (21-35) ──
    ("IPS TOMA CITOLOGIA", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA CITOLOGIA CERVICOUTERINA", "INT"),
    ("TECNICA DE TAMIZAJE", "SET"),
    ("FECHA DE TOMA DE CITOLOGIA", "DATE"),
    ("FECHA DE ENTREGA DE RESULTADO", "DATE"),
    ("OPORTUNIDAD CITOLOGIA", "INT"),
    ("REPORTE DE RESULTADO DE LA CITOLOGIA SEGUN BETHESDA", "SET"),
    ("CALIDAD EN LA MUESTRA DE CITOLOGIA CERVICOUTERINA", "SET"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA COLPOSCOPIA", "INT"),
    ("NOMBRE IPS A LA QUE TOMA COLPOSCOPIA", "TEXT"),
    ("FECHA DE REALIZACION COLPOSCOPIA", "DATE"),
    ("OPORTUNIDAD COLPOSCOPIA", "TEXT"),
    ("FECHA BIOPSIA CERVICAL", "DATE"),
    ("RESULTADO DE BIOPSIA CERVICAL", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA BIOPSIA CERVICAL", "INT"),

    # ── Citología 2 – "1" (36-50) ──
    ("IPS TOMA CITOLOGIA", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA CITOLOGIA CERVICOUTERINA", "INT"),
    ("TECNICA DE TAMIZAJE", "SET"),
    ("FECHA DE TOMA DE CITOLOGIA 1", "DATE"),
    ("FECHA DE ENTREGA DE RESULTADO", "DATE"),
    ("OPORTUNIDAD CITOLOGIA", "INT"),
    ("REPORTE DE RESULTADO DE LA CITOLOGIA SEGUN BETHESDA", "SET"),
    ("CALIDAD EN LA MUESTRA DE CITOLOGIA CERVICOUTERINA", "SET"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA COLPOSCOPIA", "INT"),
    ("NOMBRE IPS A LA QUE TOMA COLPOSCOPIA", "TEXT"),
    ("FECHA DE REALIZACION COLPOSCOPIA", "DATE"),
    ("OPORTUNIDAD", "INT"),
    ("FECHA BIOPSIA CERVICAL", "DATE"),
    ("RESULTADO DE BIOPSIA CERVICAL", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA BIOPSIA CERVICAL", "INT"),

    # ── Citología 3 – "2" (51-65) ──
    ("IPS TOMA CITOLOGIA", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA CITOLOGIA CERVICOUTERINA", "INT"),
    ("TECNICA DE TAMIZAJE", "SET"),
    ("FECHA DE TOMA DE CITOLOGIA 2", "DATE"),
    ("FECHA DE ENTREGA DE RESULTADO", "DATE"),
    ("OPORTUNIDAD CITOLOGIA", "INT"),
    ("REPORTE DE RESULTADO DE LA CITOLOGIA SEGUN BETHESDA", "SET"),
    ("CALIDAD EN LA MUESTRA DE CITOLOGIA CERVICOUTERINA", "SET"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA COLPOSCOPIA", "INT"),
    ("NOMBRE IPS A LA QUE TOMA COLPOSCOPIA", "TEXT"),
    ("FECHA DE REALIZACION COLPOSCOPIA", "DATE"),
    ("OPORTUNIDAD COLPOSCOPIA", "TEXT"),
    ("FECHA BIOPSIA CERVICAL", "DATE"),
    ("RESULTADO DE BIOPSIA CERVICAL", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA BIOPSIA CERVICAL", "INT"),

    # ── Citología 4 – "3" (66-80) ──
    ("IPS TOMA CITOLOGIA", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA CITOLOGIA CERVICOUTERINA", "INT"),
    ("TECNICA DE TAMIZAJE", "SET"),
    ("FECHA DE TOMA DE CITOLOGIA 3", "DATE"),
    ("FECHA DE ENTREGA DE RESULTADO", "DATE"),
    ("OPORTUNIDAD CITOLOGIA", "INT"),
    ("REPORTE DE RESULTADO DE LA CITOLOGIA SEGUN BETHESDA", "SET"),
    ("CALIDAD EN LA MUESTRA DE CITOLOGIA CERVICOUTERINA", "SET"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA COLPOSCOPIA", "INT"),
    ("NOMBRE IPS A LA QUE TOMA COLPOSCOPIA", "TEXT"),
    ("FECHA DE REALIZACION COLPOSCOPIA", "DATE"),
    ("OPORTUNIDAD COLPOSCOPIA", "TEXT"),
    ("FECHA BIOPSIA CERVICAL", "DATE"),
    ("RESULTADO DE BIOPSIA CERVICAL", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA BIOPSIA CERVICAL", "INT"),

    # ── Citología 5 – "4" (81-95) ──
    ("IPS TOMA CITOLOGIA", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA CITOLOGIA CERVICOUTERINA", "INT"),
    ("TECNICA DE TAMIZAJE", "SET"),
    ("FECHA DE TOMA DE CITOLOGIA 4", "DATE"),
    ("FECHA DE ENTREGA DE RESULTADO", "DATE"),
    ("OPORTUNIDAD CITOLOGIA", "INT"),
    ("REPORTE DE RESULTADO DE LA CITOLOGIA SEGUN BETHESDA", "SET"),
    ("CALIDAD EN LA MUESTRA DE CITOLOGIA CERVICOUTERINA", "SET"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA CITOLOGIA CERVICOUTERINA", "INT"),
    ("NOMBRE IPS A LA QUE TOMA COLPOSCOPIA", "TEXT"),
    ("FECHA DE REALIZACION COLPOSCOPIA", "DATE"),
    ("OPORTUNIDAD COLPOSCOPIA", "TEXT"),
    ("FECHA BIOPSIA CERVICAL", "DATE"),
    ("RESULTADO DE BIOPSIA CERVICAL", "TEXT"),
    ("CODIGO DE HABILITACION IPS DONDE SE TOMA BIOPSIA CERVICAL", "INT"),

    # ── Final (96-101) ──
    ("RENUENCIA", "SET"),
    ("OBSERVACION", "TEXT"),
    ("PENDIENTE SI/NO", "TEXT"),
    ("OBJETO", "SET"),
    ("FECHA PROXIMA CITOLOGIA", "DATE"),
    ("CANTIDAD DE CITOLOGIAS", "TEXT"),
]

ALLOWED_BY_NAME = {
    "TIPO DE DOCUMENTO DE IDENTIDAD": ["CC", "TI", "CE", "RC", "PA", "MSI", "ASI", "CD"],
    "GENERO": ["FEMENINO", "MASCULINO", "TRANSGENERO"],
    "ZONA AFILIACION": ["RURAL", "URBANA"],
    "REGIMEN DE AFILIACION": ["SUBSIDIADO", "CONTRIBUTIVO"],
    "ETNIA": ["WAYUU", "ARHUACO", "WIWA", "YUKPA", "KOGI", "INGA", "KANKUAMO", "CHIMILA", "ZENU", "SIN ETNIA"],
    "TECNICA DE TAMIZAJE": ["CITOLOGIA CERVICOUTERINA", "DN-VPH", "VER Y TRATAR"],
    "REPORTE DE RESULTADO DE LA CITOLOGIA SEGUN BETHESDA": [
        "ASC-US (CELULAS ESCAMOSAS ATIPICAS DE SIGNIFICADO INDETERMINADO)",
        "ASC-H (CELULAS ESCAMOSAS ATIPICAS, DE SIGNIFICADO INDETERMINADO SUGESTIVO DE LEI DE ALTO GRADO)",
        "LESION INTRAEPITELIAL ESCAMOSA (LEI) DE BAJO GRADO- HPV (NIC I) (LEI BG)",
        "LESION INTRAEPITELIAL ESCAMOSA (LEI) DE ALTO GRADO (NIC II-III CA INSITU) (LEI AG)",
        "LESION INTRAEPITELIAL ESCAMOSA DE ALTO GRADO SOSPECHOSA DE INFILTRACION",
        "CARCINOMA DE CELULAS ESCAMOSAS (ESCAMOCELULAR) GLANDULARES",
        "CELULAS ENDOCERVICALES ATIPICAS SIN NINGUN OTRO SIGNIFICADO",
        "CELULAS ENDOMETRIALES ATIPICAS SIN NINGUN OTRO SIGNIFICADO",
        "CELULAS GLANDULARES ATIPICAS SIN NINGUN OTRO SIGNIFICADO",
        "CELULAS ENDOCERVICALES ATIPICAS SOSPECHOSAS DE NEOPLASIA",
        "CELULAS ENDOMETRIALES ATIPICAS SOSPECHOSAS DE NEOPLASIA",
        "CELULAS GLANDULARES ATIPICAS SOSPECHOSAS DE NEOPLASIA",
        "ADENOCARCINOMA ENDOCERVICAL IN SITU",
        "ADENOCARCINOMA ENDOCERVICAL",
        "ADENOCARCINOMA ENDOMETRIAL",
        "OTRAS NEOPLASIAS",
        "NEGATIVA PARA LESION INTRAEPITELIAL O NEOPLASIA",
        "INADECUADA PARA LECTURA",
        "PENDIENTE RESULTADO",
        "SIN DATO",
    ],
    "CALIDAD EN LA MUESTRA DE CITOLOGIA CERVICOUTERINA": [
        "SATISFACTORIA ZONA DE TRANSFORMACION PRESENTE",
        "SATISFACTORIA ZONA DE TRANSFORMACION AUSENTE",
        "INSATISFACTORIA",
    ],
    "RENUENCIA": ["SI", "NO", "NO APLICA"],
    "OBJETO": ["SI", "NO", "NO APLICA"],
}

def allowed_for(field_name: str):
    return ALLOWED_BY_NAME.get(field_name, SI_NO)

def build_citologia_template():
    template = []
    seen: dict[str, int] = {}

    for base_name, field_type in RAW_FIELDS:
        base = base_name.strip().upper()
        count = seen.get(base, 0) + 1
        seen[base] = count
        unique_name = base if count == 1 else f"{base}_{count}"

        allowed = None
        if field_type == "SET":
            allowed = allowed_for(base)

        template.append(field(unique_name, field_type, True, allowed))

    return template

def get_citologia_template():
    return build_citologia_template()
