from __future__ import annotations


def field(name: str, type_: str, required: bool = True, allowed: list[str] | None = None):
    return {
        "name": name.strip(),
        "type": type_,
        "required": required,
        **({"allowed": allowed} if allowed else {}),
    }


SI_NO = ["SI", "NO"]
SI_NO_SD = ["SI", "NO", "SIN DATO"]
PN_SD = ["POSITIVO", "NEGATIVO", "SIN DATO"]


RAW_FIELDS: list[tuple[str, str]] = [
    ("No", "INT"),
    ("Tipo de documento de identidad", "SET"),
    ("No. De Identificación", "INT"),
    ("Apellido_1,", "TEXTO"),
    ("Apellido_2", "TEXTO"),
    ("Nombre_1,", "TEXTO"),
    ("Nombre_2", "TEXTO"),
    ("Fecha de Nacimiento", "FECHA"),
    ("Edad (años)", "FORMULA"),
    ("Sexo", "SET"),
    ("Regimen Afiliacion", "SET"),
    ("Pertenecia Etnica", "SET"),
    ("Grupo Poblacional", "TEXTO"),
    ("Departamento Residencia", "TEXTO"),
    ("Municipio de Residencia", "TEXTO"),
    ("Zona", "SET"),
    ("Etnia", "SET"),
    ("Asentamiento / Rancheria / Comunidad", "TEXTO"),
    ("Teléfono usuaria", "INT"),
    ("Direccion", "TEXTO"),
    ("Nivel Educativo", "SET"),
    ("Discapacidad", "SET"),
    ("Mujer cabeza de Hogar", "SET"),
    ("Ocupación", "TEXTO"),
    ("Estado Civil", "SET"),
    ("Control  Tradicional", "SET"),
    ("Gestante Renuente", "SET"),
    ("Inasistente", "SET"),
    ("Nombre de la IPS Primaria", "TEXTO"),
    ("Fecha de diagnostico", "FECHA"),
    ("Fecha de Ingreso al Control Prenatal", "FECHA"),
    ("FUM", "FECHA"),
    ("FPP", "FORMULA"),
    ("Dias para el parto", "FORMULA"),
    ("Alarma", "FORMULA"),
    ("Edad Gest Inicio Control", "FORMULA"),
    ("Trimestre inicio control", "INT"),
    ("P", "INT"),
    ("C", "INT"),
    ("A", "INT"),
    ("M", "INT"),
    ("V", "INT"),
    ("Diabetes", "SET"),
    ("VIH", "SET"),
    ("Sifilis", "SET"),
    ("Tuberculosis", "SET"),
    ("Otras condiciones medicas graves", "SET"),
    ("Si la respuesta anterior es  SI describa la otra condición médica grave", "TEXTO"),
    ("Antecedentes de eventos obstétricos\ndesfavorables", "SET"),
    ("Periodo Intergenésico", "SET"),
    ("Peso Inicial (kg)", "DECIMAL"),
    ("Talla (metros)", "DECIMAL"),
    ("Indice de Masa Corporal (IMC)", "FORMULA"),
    ("Clasificación del IMC", "FORMULA"),
    ("Embarazo deseado", "SET"),
    ("Hábitos de riesgo", "SET"),
    ("Ha sido victima de violencia fisica o psicologica", "SET"),
    ("Ha sido victima de abuso sexual", "SET"),
    ("Se Identifican Causales Para IVE?", "SET"),
    ("RIESGO OBSTETRICO", "SET"),
    ("Causas de Alto  Riesgo Obstetrico", "SET"),
    ("RIESGO DE PREECLAMPSIA", "SET"),
    ("Causas de Alto  Riesgo de preeclampsia", "SET"),
    ("RIESGO TROMBOEMBOLICO", "SET"),
    ("Causas de Alto  Riesgo Tromboembolico", "SET"),
    ("fecha de suministro de tratamiento", "FECHA"),
    ("tratamiento Instaurado", "TEXTO"),
    ("Remitida a especialista?", "SET"),
    ("Describa cual(es) especialistas la han atendido", "TEXTO"),
    ("Trimestre Asesoria VIH", "INT"),
    ("Fecha Toma Prueba VIH Primer Tamizaje", "FECHA"),
    ("Resultado Primer Tamizaje prueba de VIH", "SET"),
    ("Trimestre Toma Prueba VIH Primer Tamizaje", "INT"),
    ("Fecha Toma Prueba VIH Segundo Tamizaje", "FECHA"),
    ("Resultado Segundo Tamizaje Prueba de VIH", "SET"),
    ("Trimestre Toma  Prueba VIH Segundo Tamizaje", "INT"),
    ("Fecha Toma Prueba VIH Tercer Tamizaje", "FECHA"),
    ("Resultado Tercer Tamizaje Prueba de VIH", "SET"),
    ("Trimestre Toma Prueba VIH Tercer Tamizaje", "INT"),
    ("Resultado Primera Prueba Treponemica Rápida Sífilis", "SET"),
    ("Trimestre Primera Prueba Treponemica Rapida Sifilis", "INT"),
    ("Fecha Segunda Prueba Treponemica Rapida Sifilis", "FECHA"),
    ("Resultado Segunda Prueba Treponemica Rápida Sífilis", "SET"),
    ("Trimestre Segunda Prueba Treponemica Rapida Sifilis", "INT"),
    ("Fecha Tercera Prueba Treponemica Rapida Sifilis", "FECHA"),
    ("Resultado Tercera Prueba Treponemica Rápida Sífilis", "SET"),
    ("Trimestre Tercera Prueba Treponemica Rapida Sifilis", "INT"),
    ("Resultado Toma Segunda Prueba VIH", "SET"),
    ("Trimestre Toma segunda Prueba VIH", "INT"),
    ("Fecha prueba confirmatoria Según Algoritmo", "FECHA"),
    ("Trimestre Prueba confirmatoria Según Algoritmo", "INT"),
    ("Tratamiento instaurado", "TEXTO"),
    ("Fecha de inicio del tratamiento", "FECHA"),
    ("Fecha de segunda dosis del tratamiento", "FECHA"),
    ("Fecha de tercera dosis del tratamiento", "FECHA"),
    ("Resultado Urocultivo", "SET"),
    ("Resultado Glicemia", "SET"),
    ("Resultado Prueba de Tolerancia Oral Glucosa", "SET"),
    ("Resultado 1ra Hemoglobina", "SET"),
    ("Fecha 2da Realizacion Hemoglobina", "FECHA"),
    ("Resultado 2da Hemoglobina", "SET"),
    ("Fecha 3ra Realizacion Hemoglobina", "FECHA"),
    ("Resultado 3ra Hemoglobina", "SET"),
    ("Resultado Antigeno Superficie Hepatitis B", "SET"),
    ("Resultado Toxoplasma", "SET"),
    ("Resultado Rubeola", "SET"),
    ("Resultado Tamizaje de cuello uterino", "SET"),
    ("Resultado Prueba de Tamizaje para Estreptococo Grupo B", "SET"),
    ("Resultado Gota gruesa (Malaria)", "SET"),
    ("Resultado Chagas", "SET"),
    ("FECHA DE APLICACIÓN TOXOIDE Según Antecedente Vacunal", "FECHA"),
    ("FECHA DE APLICACIÓN DPT ACELULAR (Semana 26)", "FECHA"),
    ("FECHA DE APLICACIÓN COVID-19     (1 En la Gestación)", "FECHA"),
    ("FECHA DE APLICACIÓN VSR (Semana 28 - 36)", "FECHA"),
    ("FECHA CONSULTA ODONTOLOGICA", "FECHA"),
    ("Ecografia Obstetrica para la detección de anomalias estructurales (18 - 23)", "TEXTO"),
    ("Otras ecografías?", "TEXTO"),
    ("Fecha suministro Calcio (Semana 14)", "FECHA"),
    ("Fecha suministro Hierro", "FECHA"),
    ("Fecha suministro", "FECHA"),
    ("Fecha Desparasitación Antihelmintica II y III Trimestre (Albendazo 400 Mg Dosis Unica)", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("Fecha 2do Control", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("Fecha 3er Control", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("Fecha 4to Control", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("Fecha 5to Control", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("Fecha 6to Control", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("Fecha 7mo Control", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("fecha 8vo Control", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("Fecha 9no Control", "FECHA"),
    ("Quien Realizó el Control", "TEXTO"),
    ("Número Total de Controles Prenatales", "FORMULA"),
    ("Ultimo Control Prenatal", "FORMULA"),
    ("Edad Gestacional actual", "FORMULA"),
    ("Peso Actual", "DECIMAL"),
    ("Talla actual", "DECIMAL"),
    ("IMC", "DECIMAL"),
    ("TA ACTUAL", "TEXTO"),
    ("ALTURA UTERINA", "DECIMAL"),
    ("FRECUENCIA CARDIACA FETAL", "DECIMAL"),
    ("Fecha Segunda Consulta Ginecología", "FECHA"),
    ("Fecha Tercera Consulta Ginecología", "FECHA"),
    ("Fecha Consulta Nutrición", "FECHA"),
    ("Fecha Consulta Psicología", "FECHA"),
    ("Fecha de Atención Otro Especialista", "FECHA"),
    ("Quien Realizó la Consulta", "TEXTO"),
    ("Tipo", "SET"),
    ("Fecha", "FECHA"),
    ("Semanas de Gestación", "INT"),
    ("Complicaciones", "SET"),
    ("Fecha de Parto", "FECHA"),
    ("Caracteristicas del parto", "SET"),
    ("Parto atendido por", "SET"),
    ("No. Semanas de gestación", "INT"),
    ("Multiplicidad del embarazo", "SET"),
    ("Complicaciones durante el parto", "SET"),
    ("Tipo Complicación", "SET"),
    ("UCI  Materna", "SET"),
    ("Toma de pruebas ITS intraparto", "SET"),
    ("Resultado POSITIVO", "SET"),
    ("Fecha", "FECHA"),
    ("Causa de la defunción", "TEXTO"),
    ("TIPO", "SET"),
    ("FECHA", "FECHA"),
    ("RENUENTE A PLANIFICACION FAMILIAR", "SET"),
]


ALLOWED_BY_NAME = {
    "Tipo de documento de identidad": ["CC", "MS", "RC", "TI", "PA", "CD", "AS"],
    "Sexo": ["FEMENINO", "MASCULINO"],
    "Regimen Afiliacion": ["Subsidiado: S", "Contributivo: C"],
    "Pertenecia Etnica": ["Indígena", "ROM (Gitano)", "Raizal del Archipielago", "Negro (a), Mulato, Afroamericano", "Mestizo", "Ningunas de las Anteriores"],
    "Zona": ["Rural", "Urbana"],
    "Etnia": ["Wayuu", "Arhuaco", "Wiwa", "Yukpa", "Kogi", "Inga", "Kankuamo", "Chimila", "Zenu", "Sin Etnia"],
    "Nivel Educativo": ["Analfabeta", "Sabe Leer o Escribir", "Primaria Completa", "Primaria Incompleta", "Secundaria Completa", "Secundaria Incompleta", "Técnico", "Tecnólogo", "Profesional Universitario"],
    "Discapacidad": ["Discapacidad fisica", "Discapacidad Psiquica", "Discapacidad mental", "Ninguna", "Sin dato"],
    "Mujer cabeza de Hogar": ["Si", "No"],
    "Estado Civil": ["Soltera", "Casada", "Divorciada", "Viuda", "Unión Libre"],
    "Control  Tradicional": ["Sabedor Ancestral", "Partera (o)", "Sobandera (o)"],
    "Gestante Renuente": ["Si", "No"],
    "Inasistente": ["Si", "No"],
    "Diabetes": ["SI", "NO"],
    "VIH": ["SI", "NO"],
    "Sifilis": ["SI", "NO"],
    "Tuberculosis": ["SI", "NO"],
    "Otras condiciones medicas graves": ["SI", "NO"],
    "Antecedentes de eventos obstétricos\ndesfavorables": ["Prematurez", "Malformados", "Placenta previa", "Polihidramnios", "Muerte Fetal o neonatal", "Bajo peso al nacer", "Ninguno"],
    "Periodo Intergenésico": ["Ninguno", "<12 meses", "12 a 24 meses", "25 a 48 meses", "49 y mas", "Sin dato"],
    "Embarazo deseado": ["SI", "NO"],
    "Hábitos de riesgo": ["SI", "NO"],
    "Ha sido victima de violencia fisica o psicologica": ["SI", "NO"],
    "Ha sido victima de abuso sexual": ["SI", "NO"],
    "Se Identifican Causales Para IVE?": ["SI", "NO"],
    "RIESGO OBSTETRICO": ["SI", "NO"],
    "Causas de Alto  Riesgo Obstetrico": ["-primigestante adolescente", "-Embarazo no Deseado", "-Gestante Añosa", "-antecedente de preeclampsia", "-Periodo Intergénesico corto", "-Incompatibilidad grupo Rh", "-enfermedad autoimune", "-embarazo multiple", "-Multíparidad                                                                                                                                                                                                                                                                                                                                                  -cesarea anterior", "-enfermedad renal", "-Antecedentes  de MME", "-Antecedentes de Malformación Congénita", "-Sobrepeso, Obesidad", "-HTA Crónica", "-Hipertensión Inducida por el Embarazo", "-Diabetes", "-VIH", "-Sífilis", "-Hepatitis B", "-enfermedad de chagas", "-Tuberculosis", "-Cancer", "-LES", "-ERC", "-Enfermedad Huérfana", "-Enfermedad Mental", "-Antecedentes de aborto", "-Víctima de Violencia Física o Psicológica", "-Víctima de Violencia Sexual", "-Fumadora", "-Consumo de Alcohol", "-Consumo de SPA", "-Antecedente de mortinato"],
    "RIESGO DE PREECLAMPSIA": ["SI", "NO"],
    "Causas de Alto  Riesgo de preeclampsia": ["-primigestante adolescente", "-Embarazo no Deseado", "-Gestante Añosa", "-antecedente de preeclampsia", "-Periodo Intergénesico corto", "-Incompatibilidad grupo Rh", "-enfermedad autoimune", "-embarazo multiple", "-Multíparidad                                                                                                                                                                                                                                                                                                                                                  -cesarea anterior", "-enfermedad renal", "-Antecedentes  de MME", "-Antecedentes de Malformación Congénita", "-Sobrepeso, Obesidad", "-HTA Crónica", "-Hipertensión Inducida por el Embarazo", "-Diabetes", "-VIH", "-Sífilis", "-Hepatitis B", "-enfermedad de chagas", "-Tuberculosis", "-Cancer", "-LES", "-ERC", "-Enfermedad Huérfana", "-Enfermedad Mental", "-Antecedentes de aborto", "-Víctima de Violencia Física o Psicológica", "-Víctima de Violencia Sexual", "-Fumadora", "-Consumo de Alcohol", "-Consumo de SPA", "-Antecedente de mortinato"],
    "RIESGO TROMBOEMBOLICO": ["SI", "NO"],
    "Causas de Alto  Riesgo Tromboembolico": ["ALTO RIESGO TROMBOEMBOLICO", "BAJO RIESGO TROMBOEMBOLICO"],
    "Remitida a especialista?": ["Si", "No"],
    "Resultado Primer Tamizaje prueba de VIH": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Segundo Tamizaje Prueba de VIH": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Tercer Tamizaje Prueba de VIH": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Primera Prueba Treponemica Rápida Sífilis": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Segunda Prueba Treponemica Rápida Sífilis": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Tercera Prueba Treponemica Rápida Sífilis": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Toma Segunda Prueba VIH": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Urocultivo": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Glicemia": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Prueba de Tolerancia Oral Glucosa": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado 1ra Hemoglobina": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado 2da Hemoglobina": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado 3ra Hemoglobina": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Antigeno Superficie Hepatitis B": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Toxoplasma": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Rubeola": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Tamizaje de cuello uterino": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Prueba de Tamizaje para Estreptococo Grupo B": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Gota gruesa (Malaria)": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Resultado Chagas": ["POSITIVO", "NEGATIVO", "SIN DATO"],
    "Tipo": ["DIU", "Inyeccion mensual", "Inyeccion trimestral", "Pildoras", "Condon", "Pomeroy", "Ninguno"],
    "Complicaciones": ["Si", "No"],
    "Caracteristicas del parto": ["Parto Vaginal", "Cesarea", "NA"],
    "Parto atendido por": ["IPS baja complejidad", "IPS mediana o alta", "Partera", "Medico Tradicional", "Otro"],
    "Multiplicidad del embarazo": ["Simple", "Doble", "Triple", "Cuadruple o más"],
    "Complicaciones durante el parto": ["Si", "No"],
    "Tipo Complicación": ["Parto prematuro", "RPM", "Hemorragia", "Anomalías del cordón", "Anomalías de la placenta", "Sufrimiento fetal", "Desproporción C-P", "Otras"],
    "UCI  Materna": ["Si", "No"],
    "Toma de pruebas ITS intraparto": ["No", "Sifilis", "VIH", "Sífilis y VIH"],
    "Resultado POSITIVO": ["Si", "No"],
    "TIPO": ["DIU", "Inyeccion mensual", "Inyeccion trimestral", "Pildoras", "Condon", "Pomeroy", "Ninguno"],
    "RENUENTE A PLANIFICACION FAMILIAR": ["Si", "No"],
}


def allowed_for(field_name: str):
    direct = ALLOWED_BY_NAME.get(field_name)
    if direct is not None:
        return direct
    # Buscar case-insensitive y sin acentos
    norm = {str(k).strip().upper(): v for k, v in ALLOWED_BY_NAME.items()}
    return norm.get(field_name.upper(), SI_NO)


def build_gestante_template():
    template = []
    seen: dict[str, int] = {}

    for base_name, field_type in RAW_FIELDS:
        base = base_name.strip()
        count = seen.get(base, 0) + 1
        seen[base] = count
        unique_name = base if count == 1 else f"{base}_{count}"

        allowed = None
        if field_type == "SET":
            allowed = allowed_for(base)

        template.append(field(unique_name, field_type, True, allowed))

    return template


def get_gestante_template():
    return build_gestante_template()
