from __future__ import annotations


def field(name: str, type_: str, required: bool = True, allowed: list[str] | None = None):
    return {
        "name": name.strip(),
        "type": type_,
        "required": required,
        **({"allowed": allowed} if allowed else {}),
    }


RAW_FIELDS: list[tuple[str, str]] = [
    ("No", "INT"),
    ("Tipo de documento de identidad", "SET"),
    ("No. De Identificación", "INT"),
    ("Apellido_1,", "TEXT"),
    ("Apellido_2", "TEXT"),
    ("Nombre_1,", "TEXT"),
    ("Nombre_2", "TEXT"),
    ("Fecha de Nacimiento", "DATE"),
    ("Edad (años)", "FORMULA"),
    ("Sexo", "SET"),
    ("Regimen Afiliacion", "SET"),
    ("Pertenecia Etnica", "SET"),
    ("Grupo Poblacional", "TEXT"),
    ("Departamento Residencia", "TEXT"),
    ("Municipio de Residencia", "TEXT"),
    ("Zona", "SET"),
    ("Etnia", "SET"),
    ("Asentamiento/Rancheria/Comunidad", "TEXT"),
    ("Teléfono usuaria", "INT"),
    ("Direccion", "TEXT"),
    ("Nivel Educativo", "SET"),
    ("Discapacidad", "SET"),
    ("Mujer cabeza de Hogar", "SET"),
    ("Ocupación", "TEXT"),
    ("Estado Civil", "SET"),
    ("Control Tradicional", "SET"),
    ("Gestante Renuente", "SET"),
    ("Inasistente", "SET"),
    ("Nombre de la IPS Primaria", "TEXT"),
    ("Fecha de Diagnostico del embarazo", "DATE"),
    ("Fecha de Ingreso al Control Prenatal", "DATE"),
    ("FUM", "DATE"),
    ("FPP", "FORMULA"),
    ("Dias para el parto", "FORMULA"),
    ("Alarma", "FORMULA"),
    ("Edad Gest Inicio Control", "FORMULA"),
    ("Trimestre inicio control", "FORMULA"),
    ("G", "INT"),
    ("P", "INT"),
    ("C", "INT"),
    ("A", "INT"),
    ("M", "INT"),
    ("V", "INT"),
    ("Hipertension arterial", "SET"),
    ("Diabetes", "SET"),
    ("VIH", "SET"),
    ("Sifilis", "SET"),
    ("Tuberculosis", "SET"),
    ("Otras condiciones medicas graves", "SET"),
    ("Si la respuesta anterior es  SI describa la otra condición médica grave", "TEXT"),
    ("Antecedentes de eventos obstétricos\ndesfavorables", "SET"),
    ("Periodo Intergenésico", "SET"),
    ("Peso Inicial (kg)", "DECIMAL"),
    ("Talla (metros)", "DECIMAL"),
    ("Indice de Masa Corporal (IMC)", "FORMULA"),
    ("Clasificación del IMC", "FORMULA"),
    ("HISTORIA REPRODUCTVA", "TEXT"),
    ("EMBARAZO ACTUAL", "TEXT"),
    ("RIESGO PSICOSOCIAL", "TEXT"),
    ("PUNTAJE TOTAL", "TEXT"),
    ("Solicita ive IVE?", "SET"),
    ("Clasificación del riesgo obstetrico", "SET"),
    ("Causas de Alto Riesgo obstetrico", "SET"),
    ("Clacificacion del riesgo de preeclampsia", "SET"),
    ("Causas de Alto Riesgo de preeclampsia", "SET"),
    ("Clacificacion del riesgo tromboembolico", "SET"),
    ("Causas de Alto Riesgo tromboembolico", "SET"),
    ("fecha de suministro de tratamiento", "DATE"),
    ("tratamiento Instaurado", "TEXT"),
    ("Remitida a especialista?", "SET"),
    ("Describa cual(es) especialistas la han atendido", "TEXT"),
    ("Asesoria Prueba VIH", "DATE"),
    ("Trimestre Asesoria VIH", "FORMULA"),
    ("Fecha Toma Prueba VIH Primer Tamizaje", "DATE"),
    ("Resultado Primer Tamizaje prueba de VIH", "SET"),
    ("Trimestre Toma Prueba VIH Primer Tamizaje", "FORMULA"),
    ("Fecha Toma Prueba VIH Segundo Tamizaje", "DATE"),
    ("Resultado Segundo Tamizaje Prueba de VIH", "SET"),
    ("Trimestre Toma Prueba VIH Segundo Tamizaje", "FORMULA"),
    ("Fecha Toma Prueba VIH Tercer Tamizaje", "DATE"),
    ("Resultado Tercer Tamizaje Prueba de VIH", "SET"),
    ("Trimestre Toma Prueba VIH Tercer Tamizaje", "FORMULA"),
    ("Fecha Primera Prueba Treponemica Rapida Sifilis", "DATE"),
    ("Resultado Primera Prueba Treponemica Rapida Sifilis", "SET"),
    ("Trimestre Primera Prueba Treponemica Rapida Sifilis", "FORMULA"),
    ("Fecha Segunda Prueba Treponemica Rapida Sifilis", "DATE"),
    ("Resultado Segunda Prueba Treponemica Rapida Sifilis", "SET"),
    ("Trimestre Segunda Prueba Treponemica Rapida Sifilis", "FORMULA"),
    ("Fecha Tercera Prueba Treponemica Rapida Sifilis", "DATE"),
    ("Resultado Tercera Prueba Treponemica Rapida Sifilis", "SET"),
    ("Trimestre Tercera Prueba Treponemica Rapida Sifilis", "FORMULA"),
    ("Fecha toma Segunda Prueba VIH", "DATE"),
    ("Resultado Toma Segunda Prueba VIH", "SET"),
    ("Trimestre Toma segunda Prueba VIH", "FORMULA"),
    ("Fecha prueba confirmatoria Según Algoritmo", "DATE"),
    ("Trimestre Prueba confirmatoria Según Algoritmo", "FORMULA"),
    ("Fecha de diagnóstico de sífilis", "DATE"),
    ("Tratamiento instaurado", "TEXT"),
    ("Fecha de inicio del tratamiento", "DATE"),
    ("Fecha de segunda dosis del tratamiento", "DATE"),
    ("Fecha de tercera dosis del tratamiento", "DATE"),
    ("Fecha de Toma de Urocultivo", "DATE"),
    ("Resultado Urocultivo", "SET"),
    ("Fecha Toma Glicemia", "DATE"),
    ("Resultado Glicemia", "INT"),
    ("Fecha Prueba de Tolerancia Oral Glucosa", "DATE"),
    ("Resultado Prueba de Tolerancia Oral Glucosa", "INT"),
    ("Fecha 1ra Realizacion Hemoglobina", "DATE"),
    ("Resultado 1ra Hemoglobina", "INT"),
    ("Fecha 2da Realizacion Hemoglobina", "DATE"),
    ("Resultado 2da Hemoglobina", "INT"),
    ("Fecha 3ra Realizacion Hemoglobina", "DATE"),
    ("Resultado 3ra Hemoglobina", "INT"),
    ("Resultado Realizacion Hemoclasificación (Factor RH)", "SET"),
    ("Fecha de Antigeno Superficie Hepatitis B", "DATE"),
    ("Resultado Antigeno Superficie Hepatitis B", "SET"),
    ("Fecha Tamizaje Toxoplasma", "DATE"),
    ("Resultado Toxoplasma", "SET"),
    ("Fecha Citologia Cervicouterina", "DATE"),
    ("Resultado Tamizaje de cuello uterino", "SET"),
    ("Fecha de la prueba de Rubeola", "DATE"),
    ("Resultado Rubeola", "SET"),
    ("Fecha Prueba de Tamizaje para Estreptococo Grupo B", "DATE"),
    ("Resultado Prueba de Tamizaje para Estreptococo Grupo B", "SET"),
    ("Fecha Toma de Gota Gruesa (Malaria)", "DATE"),
    ("Resultado Gota gruesa (Malaria)", "SET"),
    ("Fecha de Realización Tamizaje Chagas", "DATE"),
    ("Resultado Chagas", "SET"),
    ("FECHA DE APLICACIÓN INFLUENZA (Desde Semana 14)", "DATE"),
    ("FECHA DE APLICACIÓN TOXOIDE Según Antecedente Vacunal", "DATE"),
    ("FECHA DE APLICACIÓN DPT ACELULAR (Semana 26)", "DATE"),
    ("FECHA DE APLICACIÓN COVID-19 (1 En la Gestación)", "DATE"),
    ("FECHA DE APLICACIÓN VSR (Semana 28 - 36)", "DATE"),
    ("FECHA CONSULTA ODONTOLOGICA", "DATE"),
    ("Ecografia obstétrica con translucencia nucal (10,6 - 13,6)", "DATE"),
    ("Ecografia Obstetrica para la detección de anomalias estructurales (18 - 23)", "DATE"),
    ("Otras ecografías?", "DATE"),
    ("Fecha suministro Acido Folico", "DATE"),
    ("Fecha suministro Calcio (Semana 14)", "DATE"),
    ("Fecha suministro Hierro", "DATE"),
    ("Tipo de tratamiento suminitrado para anemia", "SET"),
    ("Relación entre Anemia vs tratamiento", "SET"),
    ("Condicion del suministro del ASA", "TEXT"),
    ("fecha de suministro", "DATE"),
    ("Fecha Desparasitación Antihelmintica II y III Trimestre (Albendazo 400 Mg Dosis Unica)", "DATE"),
    ("Fecha 1er Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("Fecha 2do Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("Fecha 3er Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("Fecha 4to Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("Fecha 5to Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("Fecha 6to Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("Fecha 7mo Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("fecha 8vo Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("Fecha 9no Control", "DATE"),
    ("Quien Realizó el Control", "SET"),
    ("Número Total de Controles Prenatales", "FORMULA"),
    ("Ultimo Control Prenatal", "FORMULA"),
    ("edad gestacional actual", "FORMULA"),
    ("peso actual", "DECIMAL"),
    ("talla actual", "DECIMAL"),
    ("IMC ACTUAL", "FORMULA"),
    ("Clasificación del IMC ACTUAL", "FORMULA"),
    ("TA ACTUAL", "TEXT"),
    ("ALTURA UTERINA", "DECIMAL"),
    ("FCF", "DECIMAL"),
    ("Fecha Primera Consulta Ginecología", "DATE"),
    ("Fecha Segunda Consulta Ginecología", "DATE"),
    ("Fecha Tercera Consulta Ginecología", "DATE"),
    ("Fecha Consulta Nutrición", "DATE"),
    ("Fecha Consulta Psicología", "DATE"),
    ("Fecha de Atención Otro Especialista", "DATE"),
    ("Quien Realizó la Consulta", "DATE"),
    ("Tipo", "SET"),
    ("Fecha de aborto", "DATE"),
    ("Semanas de Gestación", "INT"),
    ("Complicaciones", "SET"),
    ("Fecha de Parto", "DATE"),
    ("Caracteristicas del parto", "SET"),
    ("Parto atendido por", "SET"),
    ("No. Semanas de gestación", "INT"),
    ("Multiplicidad del embarazo", "SET"),
    ("Complicaciones durante el parto", "SET"),
    ("Tipo Complicación", "SET"),
    ("UCI Materna", "SET"),
    ("Toma de pruebas ITS intraparto", "SET"),
    ("Resultado POSITIVO", "SET"),
    ("Fecha", "DATE"),
    ("Causa de la defunción", "TEXT"),
    ("TIPO", "SET"),
    ("FECHA", "DATE"),
    ("RENUENTE A PLANIFICACION FAMILIAR", "SET"),
    ("OBSERVACIONES GENERALES", "TEXT"),
]


ALLOWED_BY_NAME = {
    "Tipo de documento de identidad": ["CC", "MS", "PT", "TI", "PA", "CD", "AS"],
    "Sexo": ["Femenino"],
    "Regimen Afiliacion": ["S", "C"],
    "Pertenecia Etnica": ["Indígena", "ROM (Gitano)", "Raizal del Archipielago", "Negro (a), Mulato, Afroamericano", "Mestizo", "Ningunas de las Anteriores"],
    "Zona": ["Rural", "Urbana"],
    "Etnia": ["NA", "Wayuu", "Arhuaco", "Wiwa", "Yukpa", "Kogi", "Inga", "Kankuamo", "Chimila", "Zenu"],
    "Nivel Educativo": ["Analfabeta", "Sabe Leer o Escribir", "Primaria Completa", "Primaria Incompleta", "Secundaria Completa", "Secundaria Incompleta", "Técnico", "Tecnólogo", "Profesional Universitario"],
    "Discapacidad": ["Discapacidad fisica", "Discapacidad Psiquica", "Discapacidad mental", "Ninguna", "Sin dato"],
    "Mujer cabeza de Hogar": ["Si", "No"],
    "Estado Civil": ["Soltera", "Casada", "Divorciada", "Viuda", "Unión Libre"],
    "Control Tradicional": ["Si", "No"],
    "Gestante Renuente": ["Si", "No"],
    "Inasistente": ["Si", "No"],
    "Hipertension arterial": ["Si", "No"],
    "Diabetes": ["Si", "No"],
    "VIH": ["Si", "No"],
    "Sifilis": ["Si", "No"],
    "Tuberculosis": ["Si", "No"],
    "Otras condiciones medicas graves": ["Si", "No"],
    "Antecedentes de eventos obstétricos\ndesfavorables": ["Prematurez", "Malformados", "Placenta previa", "Polihidramnios", "Muerte Fetal o neonatal", "Bajo peso al nacer", "Ninguno"],
    "Periodo Intergenésico": ["Ninguno", "<12 meses", "12 a 24 meses", "25 a 48 meses", "49 y mas"],
    "Solicita ive IVE?": ["Si", "No"],
    "Clasificación del riesgo obstetrico": ["Alto riesgo obstétrico", "Bajo riesgo obstétrico"],
    "Causas de Alto Riesgo obstetrico": ["NA", "-primigestante adolescente", "-Embarazo no Deseado", "-Gestante Añosa", "-antecedente de preeclampsia", "-Periodo Intergénesico corto", "-Incompatibilidad grupo Rh", "-enfermedad autoimune", "-embarazo multiple", "-Multíparidad -cesarea anterior", "-enfermedad renal", "-Antecedentes de MME", "-Antecedentes de Malformación Congénita", "-Sobrepeso, Obesidad", "-HTA Crónica", "-Hipertensión Inducida por el Embarazo", "-Diabetes", "-VIH", "-Sífilis", "-Hepatitis B", "-enfermedad de chagas", "-Tuberculosis", "-Cancer", "-LES", "-ERC", "-Enfermedad Huérfana", "-Enfermedad Mental", "-Antecedentes de aborto", "-Víctima de Violencia Física o Psicológica", "-Víctima de Violencia Sexual", "-Fumadora", "-Consumo de Alcohol", "-Consumo de SPA", "-Antecedente de mortinato"],
    "Clacificacion del riesgo de preeclampsia": ["Alto riesgo de Preeclampsia", "Moderado riesgo de preeclamsia", "Bajo riesgo de Preeclampsia"],
    "Causas de Alto Riesgo de preeclampsia": ["NA", "-primigestante adolescente", "-Embarazo no Deseado", "-Gestante Añosa", "-antecedente de preeclampsia", "-Periodo Intergénesico corto", "-Incompatibilidad grupo Rh", "-enfermedad autoimune", "-embarazo multiple", "-Multíparidad -cesarea anterior", "-enfermedad renal", "-Antecedentes de MME", "-Antecedentes de Malformación Congénita", "-Sobrepeso, Obesidad", "-HTA Crónica", "-Hipertensión Inducida por el Embarazo", "-Diabetes", "-VIH", "-Sífilis", "-Hepatitis B", "-enfermedad de chagas", "-Tuberculosis", "-Cancer", "-LES", "-ERC", "-Enfermedad Huérfana", "-Enfermedad Mental", "-Antecedentes de aborto", "-Víctima de Violencia Física o Psicológica", "-Víctima de Violencia Sexual", "-Fumadora", "-Consumo de Alcohol", "-Consumo de SPA", "-Antecedente de mortinato"],
    "Clacificacion del riesgo tromboembolico": ["Alto riesgo Tromboembolico", "Bajo riesgo Tromboembolico"],
    "Causas de Alto Riesgo tromboembolico": ["NA", "-primigestante adolescente", "-Embarazo no Deseado", "-Gestante Añosa", "-antecedente de preeclampsia", "-Periodo Intergénesico corto", "-Incompatibilidad grupo Rh", "-enfermedad autoimune", "-embarazo multiple", "-Multíparidad -cesarea anterior", "-enfermedad renal", "-Antecedentes de MME", "-Antecedentes de Malformación Congénita", "-Sobrepeso, Obesidad", "-HTA Crónica", "-Hipertensión Inducida por el Embarazo", "-Diabetes", "-VIH", "-Sífilis", "-Hepatitis B", "-enfermedad de chagas", "-Tuberculosis", "-Cancer", "-LES", "-ERC", "-Enfermedad Huérfana", "-Enfermedad Mental", "-Antecedentes de aborto", "-Víctima de Violencia Física o Psicológica", "-Víctima de Violencia Sexual", "-Fumadora", "-Consumo de Alcohol", "-Consumo de SPA", "-Antecedente de mortinato"],
    "Remitida a especialista?": ["NA", "Si", "No"],
    "Resultado Primer Tamizaje prueba de VIH": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Segundo Tamizaje Prueba de VIH": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Tercer Tamizaje Prueba de VIH": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Primera Prueba Treponemica Rapida Sifilis": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Segunda Prueba Treponemica Rapida Sifilis": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Tercera Prueba Treponemica Rapida Sifilis": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Toma Segunda Prueba VIH": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Urocultivo": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Realizacion Hemoclasificación (Factor RH)": ["NA", "O+", "O-", "A+", "A-", "AB+", "AB-", "B+", "B-"],
    "Resultado Antigeno Superficie Hepatitis B": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Toxoplasma": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Tamizaje de cuello uterino": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Rubeola": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Prueba de Tamizaje para Estreptococo Grupo B": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Gota gruesa (Malaria)": ["NA", "POSITIVO", "NEGATIVO"],
    "Resultado Chagas": ["NA", "POSITIVO", "NEGATIVO"],
    "Quien Realizó el Control": ["Médico Ginecologia", "Aux de Enfermeria", "Enfermera (o)", "Control Tradicional (obligatorio)"],
    "Tipo": ["NA", "IVE", "Expontáneo", "Provocado"],
    "TIPO": ["DIU", "Inyeccion mensual", "Inyeccion trimestral", "Pildoras", "Condon", "Pomeroy", "Ninguno", "NA", "SIN DATO"],
    "Tipo de tratamiento suminitrado para anemia": ["NA", "1. Hierro oral", "2. Hierro parenteral", "3. transfusion sanguinea"],
    "Relación entre Anemia vs tratamiento": ["1. tratamiento para anemia indicado y suministrado", "2. tratamiento para anemia indicado y no suministrado", "3. tratamiento para anemia no indicada ni suministrada", "4. NO requiere tratamiento hemoglobina adecuada"],
    "Complicaciones": ["NA", "Si", "No"],
    "Caracteristicas del parto": ["NA", "Parto Vaginal", "Cesarea"],
    "Parto atendido por": ["NA", "IPS baja complejidad", "IPS mediana o alta", "Partera", "Medico Tradicional", "Otro"],
    "Multiplicidad del embarazo": ["NA", "Simple", "Doble", "Triple", "Cuadruple o más"],
    "Complicaciones durante el parto": ["NA", "Si", "No"],
    "Tipo Complicación": ["NA", "Parto prematuro", "RPM", "Hemorragia", "Anomalías del cordón", "Anomalías de la placenta", "Sufrimiento fetal", "Desproporción C-P", "Otras"],
    "UCI Materna": ["NA", "Si", "No"],
    "Toma de pruebas ITS intraparto": ["NA", "No", "Sifilis", "VIH", "Sífilis y VIH"],
    "Resultado POSITIVO": ["NA", "Si", "No"],
    "RENUENTE A PLANIFICACION FAMILIAR": ["NA", "Si", "No"],
}


def allowed_for(field_name: str):
    direct = ALLOWED_BY_NAME.get(field_name)
    if direct is not None:
        return direct
    try:
        from .validators import normalize_text
    except ImportError:
        from validators import normalize_text
    norm = {normalize_text(k): v for k, v in ALLOWED_BY_NAME.items()}
    cn = normalize_text(field_name)
    return norm.get(cn, ["SIN DATO"])


def build_gestante_template():
    template = []
    seen: dict[str, int] = {}

    for base_name, field_type in RAW_FIELDS:
        base = base_name.strip()
        count = seen.get(base, 0) + 1
        seen[base] = count
        unique_name = base if count == 1 else f"{base}_{count}"

        allowed = None
        if field_type == "SET":
            allowed = allowed_for(base)

        template.append(field(unique_name, field_type, True, allowed))

    return template


def get_gestante_template():
    return build_gestante_template()
