"""
Script de migración para tablas de Reportes de Pendientes.
Ejecutar directamente contra la base de datos:
  python migrate_reportes.py [DATABASE_URL]

Si no se provee DATABASE_URL, usa la variable de entorno DATABASE_URL
o la URL de prueba por defecto.
"""
import os
import sys

DATABASE_URL = sys.argv[1] if len(sys.argv) > 1 else os.environ.get(
    "DATABASE_URL",
    "postgres://postgres:qazwsx12A.@129.80.159.38:5436/base_sie_dusakawi"
)

DDL = [
    # ─── reporte_consultas ────────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS reporte_consultas (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id INTEGER,
        ips_name VARCHAR(255),
        consecutivo INTEGER,
        periodo_reportado VARCHAR(20),
        cod_eps VARCHAR(60),
        tipo_documento VARCHAR(20),
        documento VARCHAR(60),
        identificador_orden VARCHAR(120),
        cod_municipio VARCHAR(10),
        cod_diagnostico VARCHAR(20),
        cups VARCHAR(20),
        procedimiento_consulta VARCHAR(255),
        clase_pendiente INTEGER,
        cantidad_ordenada INTEGER,
        cantidad_prestacion_efectiva INTEGER,
        cantidad_pendiente INTEGER,
        causa_pendiente INTEGER,
        observacion_causa TEXT,
        fecha_orden VARCHAR(20),
        fecha_pendiente VARCHAR(20),
        fecha_cierre VARCHAR(20),
        patologia VARCHAR(120),
        mecanismo_financiacion VARCHAR(60),
        tutela VARCHAR(5),
        identificacion_prestador VARCHAR(120),
        estado VARCHAR(20) NOT NULL DEFAULT 'borrador',
        activo BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    )
    """,
    # ─── reporte_medicamentos ─────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS reporte_medicamentos (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id INTEGER,
        ips_name VARCHAR(255),
        consecutivo INTEGER,
        periodo_reportado VARCHAR(20),
        cod_eps VARCHAR(60),
        tipo_documento VARCHAR(20),
        documento VARCHAR(60),
        identificador_prescripcion VARCHAR(120),
        cod_municipio VARCHAR(10),
        cod_diagnostico VARCHAR(20),
        medicamento_atc VARCHAR(60),
        medicamento_concentracion VARCHAR(60),
        medicamento_unidad VARCHAR(30),
        forma_farmaceutica VARCHAR(120),
        medicamento_nombre VARCHAR(255),
        mecanismo_financiacion VARCHAR(60),
        cantidad_prescrita INTEGER,
        dias_tratamiento INTEGER,
        cantidad_dispensada INTEGER,
        cum_medicamento VARCHAR(60),
        cantidad_pendiente INTEGER,
        causa_pendiente INTEGER,
        observacion_causa TEXT,
        fecha_prescripcion VARCHAR(20),
        fecha_pendiente VARCHAR(20),
        fecha_cierre VARCHAR(20),
        cantidad_dispensada_cierre INTEGER,
        patologia VARCHAR(120),
        identificacion_prestador VARCHAR(255),
        tutela VARCHAR(5),
        estado VARCHAR(20) NOT NULL DEFAULT 'borrador',
        activo BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    )
    """,
    # ─── reportes_audit ───────────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS reportes_audit (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        reporte_id INTEGER,
        tabla VARCHAR(50) NOT NULL,
        user_id INTEGER,
        username VARCHAR(120),
        action VARCHAR(20) NOT NULL,
        field_name VARCHAR(255),
        old_value TEXT,
        new_value TEXT,
        detail TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
]

# Índices para performance
INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_rc_ips ON reporte_consultas(ips_name)",
    "CREATE INDEX IF NOT EXISTS idx_rc_estado ON reporte_consultas(estado)",
    "CREATE INDEX IF NOT EXISTS idx_rc_activo ON reporte_consultas(activo)",
    "CREATE INDEX IF NOT EXISTS idx_rc_doc ON reporte_consultas(documento)",
    "CREATE INDEX IF NOT EXISTS idx_rm_ips ON reporte_medicamentos(ips_name)",
    "CREATE INDEX IF NOT EXISTS idx_rm_estado ON reporte_medicamentos(estado)",
    "CREATE INDEX IF NOT EXISTS idx_rm_activo ON reporte_medicamentos(activo)",
    "CREATE INDEX IF NOT EXISTS idx_rm_doc ON reporte_medicamentos(documento)",
    "CREATE INDEX IF NOT EXISTS idx_ra_tabla ON reportes_audit(tabla)",
    "CREATE INDEX IF NOT EXISTS idx_ra_reporte ON reportes_audit(reporte_id)",
]

def migrate():
    from sqlalchemy import create_engine, text
    print(f"Conectando a: {DATABASE_URL.split('@')[1] if '@' in DATABASE_URL else DATABASE_URL}")
    engine = create_engine(DATABASE_URL)
    with engine.begin() as conn:
        # Drop FK constraints si existen (IPS users no tienen ID en users)
        try:
            conn.execute(text("ALTER TABLE reporte_consultas DROP CONSTRAINT IF EXISTS reporte_consultas_user_id_fkey"))
            print("  ✓ FK constraint eliminado de reporte_consultas")
        except Exception:
            pass
        try:
            conn.execute(text("ALTER TABLE reporte_medicamentos DROP CONSTRAINT IF EXISTS reporte_medicamentos_user_id_fkey"))
            print("  ✓ FK constraint eliminado de reporte_medicamentos")
        except Exception:
            pass
        for i, ddl in enumerate(DDL):
            table_name = ["reporte_consultas", "reporte_medicamentos", "reportes_audit"][i]
            try:
                conn.execute(text(ddl))
                print(f"  ✓ Tabla {table_name} creada/verificada")
            except Exception as e:
                print(f"  ✗ Error creando {table_name}: {e}")
                raise
        for idx in INDEXES:
            try:
                conn.execute(text(idx))
            except Exception:
                pass
        print("  ✓ Índices creados/verificados")
    print("Migración completada.")

if __name__ == "__main__":
    migrate()
