from __future__ import annotations

SI_NO = ["SI", "NO"]
SI_NO_SD = ["SI", "NO", "SIN DATO"]
SI_NO_NA = ["SI", "NO", "NO APLICA"]

RAW_FIELDS = [
    ("NOMBRE_1", "TEXT"),
    ("NOMBRE_2", "TEXT"),
    ("APELLIDO_1", "TEXT"),
    ("APELLIDO_2", "TEXT"),
    ("TIPO DE IDENTIFICACIÓN", "TEXT"),
    ("NUMERO DE IDENTIFICACIÓN", "INT"),
    ("FECHA DE NACIMIENTO", "TEXT"),
    ("60 Y MAS AÑOS", "SET"),
    ("EDAD(AÑOS)", "INT"),
    ("SEXO", "SET"),
    ("REGIMEN DE AFILIACION", "SET"),
    ("PERTENENCIA ETNICA", "SET"),
    ("GRUPO POBLACIONAL", "TEXT"),
    ("ETNIA", "SET"),
    ("DEPARTAMENTO RESIDENCIA", "TEXT"),
    ("MUNICIPIO DE RESIDENCIA", "INT"),
    ("NUMERO DE TELEFONO", "INT"),
    ("ZONA DE UBICACION DE LA VIVIENDA", "SET"),
    ("DIRECCION", "TEXT"),
    ("ASENTAMIENTO/RANCHERIA/COMUNIDAD", "TEXT"),
    ("CODIGO DE LA IPS QUE HACE SEGUIMIENTO", "TEXT"),
    ("NOMBRE DE LA IPS QUE HACE SEGUIMIENTO", "TEXT"),
    ("FECHA INSCRIPCION PROGRAMA DE HTA - DM", "DATE"),
    ("FUMA", "SET"),
    ("CONSUMO DE ALCOHOL", "SET"),
    ("DX CONFIRMADO HTA", "TEXT"),
    ("FECHA DX", "DATE"),
    ("DX CONFIRMADO DM", "TEXT"),
    ("FECHA DX", "DATE"),
    ("TIPO DE DM", "SET"),
    ("ETIOLOGIA DE LA ERC", "SET"),
    ("TENSION ARTERIAL SISTOLICA AL INGRESO A BASE", "INT"),
    ("TENSION ARTERIAL DIASTOLICA AL INGRESO A BASE", "INT"),
    ("CLASIFICACION DE HTA DE INGRESO", "SET"),
    ("HTA CONTROLADA", "SET"),
    ("ULTIMO PESO", "INT"),
    ("TALLA", "INT"),
    ("IMC", "DECIMAL"),
    ("CLASIFICACION DEL IMC", "SET"),
    ("ULTIMA MEDICION DE PERIMETRO ABDOMINAL", "DECIMAL"),
    ("FACTOR DE RIESGO POR PA", "SET"),
    ("CLASIFICACION DEL RCV ACTUAL AL INGRESO A BASE", "SET"),
    ("FECHA DE CLASIFICACION DE RCV AL INGRESO A BASE", "DATE"),
    ("CLASIFICACION DEL RCV ACTUAL", "SET"),
    ("FECHA DE CLASIFICACION DE RCV", "DATE"),
    ("HEMOGRAMA", "DECIMAL"),
    ("FECHA DEL HEMOGRAMA", "DATE"),
    ("GLICEMIA BASAL", "DECIMAL"),
    ("FECHA DE GLICEMIA BASAL", "DATE"),
    ("PARCIAL DE ORINA", "SET"),
    ("FECHA PARCIAL DE ORINA", "DATE"),
    ("CREATININA  SANGRE (mg/dl)", "DECIMAL"),
    ("FECHA CREATININA  SANGRE", "DATE"),
    ("COLESTEROL TOTAL", "DECIMAL"),
    ("HDL", "DECIMAL"),
    ("LDL", "DECIMAL"),
    ("TRIGLICERIDOS", "DECIMAL"),
    ("FECHA PERFIL LIPIDICO", "DATE"),
    ("FECHA DE SOLICITUD DE HEMOGLOBINA GLICOSILADA", "DATE"),
    ("REPORTE DE HEMOGLOBINA GLICOSILADA (SOLO PARA USUARIOS CON DX DE DM)", "DECIMAL"),
    ("FECHA DE REPORTE DE HEMOGLOBINA GLICOSILADA", "DATE"),
    ("DM CONTROLADA", "SET"),
    ("ALBUMINURIA", "INT"),
    ("FECHA ALBUMINURIA", "DATE"),
    ("REPORTE DE EKG", "SET"),
    ("FECHA DE EKG", "DATE"),
    ("ECOCARDIOGRAMA", "SET"),
    ("FECHA DE REPORTE DEL ECOCARDIOGRAMA", "DATE"),
    ("AJUSTE TFG POR GENERO", "DECIMAL"),
    ("TFG AJUSTADA POR GENERO FORMULA COCKCROFT AND GAULT", "DECIMAL"),
    ("TFG FORMULA COCKCROFT AND GAULT ACTUAL", "DECIMAL"),
    ("TFG FORMULA COCKCROFT AND GAULT ANTERIOR", "TEXT"),
    ("VARIABILIDAD", "TEXT"),
    ("FECHA CREATININA ACTUAL", "DATE"),
    ("CREATININA ACTUAL", "DECIMAL"),
    ("FECHA CREATINNINA ANTERIOR", "DATE"),
    ("CREATININA ANTERIOR", "DECIMAL"),
    ("ESTADIO SEGUN TFG", "SET"),
    ("DESCRIPCION DEL DANO RENAL", "TEXT"),
    ("ENERO FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("FEBRERO FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("MARZO FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("ABRIL FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("MAYO FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("JUNIO FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("JULIO FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("AGOSTO FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("SEPTIEMBRE FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("OCTUBRE FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("NOVIEMBRE FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("DICIEMBRE FECHA", "DATE"),
    ("CONTROL REALIZADO POR", "SET"),
    ("FECHA DE PROXIMO CONTROL", "DATE"),
    ("ULTIMA TENSION ARTERIAL SISTOLICA", "INT"),
    ("ULTIMA TENSION ARTERIAL DIASTOLICA", "INT"),
    ("CLASIFICACION DE HTA", "SET"),
    ("FECHA DE LA ULTIMA TOMA DE PRESION ARTERIAL REPORTADO EN HISTORIA CLINICA", "DATE"),
    ("HTA CONTROLADA", "SET"),
    ("TRATAMIENTO ANTIHIPERTENSIVO Y/O DIABETES MELLITUS", "TEXT"),
    ("ADHERENCIA AL TRATAMIENTO FARMACOLOGICO (TEST DE MORISKY GREEN)", "SET"),
    ("REMITIDO A", "TEXT"),
    ("FECHA DE REMISION", "DATE"),
    ("COMPLICACIONES", "TEXT"),
    ("NOVEDADES", "SET"),
    ("CAUSA DE MUERTE", "TEXT"),
    ("FECHA DE MUERTE", "DATE"),
    ("OBSERVACIONES", "TEXT"),
]

ALLOWED_BY_NAME = {
    "60 Y MAS AÑOS": SI_NO_NA,
    "SEXO": ["FEMENINO", "MASCULINO"],
    "REGIMEN DE AFILIACION": ["SUBSIDIADO", "CONTRIBUTIVO"],
    "PERTENENCIA ETNICA": ["INDIGENA", "MESTIZO", "NINGUNAS DE LAS ANTERIORES"],
    "GRUPO POBLACIONAL": [
        "CABEZA DE FAMILIA", "JOVENES VULNERABLES", "POBLACION INFANTIL A CARGO DEL ICBF",
        "MUJER CABEZA DE HOGAR", "DISCAPACITADOS", "OTRO GRUPO POBLACIONAL",
        "DESMOVILIZADOS", "ADULTO MAYOR",
    ],
    "ETNIA": ["WAYUU", "ARHUACO", "WIWA", "YUKPA", "KOGI", "INGA", "KANKUAMO", "CHIMILA", "ZENU", "SIN ETNIA"],
    "ZONA DE UBICACION DE LA VIVIENDA": ["RURAL", "URBANA"],
    "FUMA": SI_NO_NA,
    "CONSUMO DE ALCOHOL": SI_NO_NA,
    "TIPO DE DM": ["TIPO 1 INSULINODEPENDIENTE", "TIPO 2 NO INSULINODEPENDIENTE", "NO APLICA"],
    "ETIOLOGIA DE LA ERC": ["HTA O DM", "AUTOINMUNE", "NEFROPATIA OBSTRUCTIVA", "ENFERMEDAD POLIQUISTICA", "NO TIENE ERC", "OTRAS"],
    "CLASIFICACION DE HTA DE INGRESO": ["ESTADIO1", "ESTADIO2", "ESTADIO3", "NORMAL", "SIN DATO"],
    "HTA CONTROLADA": SI_NO_SD,
    "CLASIFICACION DEL IMC": ["BAJO PESO (<18.5)", "NORMAL (18.5-24.9)", "SOBREPESO (25.0-29.9)", "OBESIDAD (30.0 O MAS)"],
    "FACTOR DE RIESGO POR PA": ["CLASIFICACION DEL RIESGO ALTO", "CLASIFICACION DEL RIESGO BAJO"],
    "CLASIFICACION DEL RCV ACTUAL AL INGRESO A BASE": ["RIESGO ALTO", "RIESGO BAJO", "RIESGO MODERADO", "NO SE CLASIFICO"],
    "CLASIFICACION DEL RCV ACTUAL": ["RIESGO ALTO", "RIESGO BAJO", "RIESGO MODERADO", "NO SE CLASIFICO"],
    "PARCIAL DE ORINA": ["NORMAL", "PROTEINURA", "HEMATURIA", "OTRA", "SIN DATO"],
    "DM CONTROLADA": SI_NO_NA,
    "REPORTE DE EKG": ["NORMAL", "ANORMAL", "SIN DATO"],
    "ECOCARDIOGRAMA": SI_NO_SD,
    "ESTADIO SEGUN TFG": ["ESTADIO1", "ESTADIO2", "ESTADIO3", "ESTADIO4", "ESTADIO5", "SIN DATO"],
    "CONTROL REALIZADO POR": ["INTERNISTA", "MEDICO GENERAL", "NUTRICIONISTA", "ENFERMERIA", "SIN DATO"],
    "CLASIFICACION DE HTA": ["ESTADIO1", "ESTADIO2", "HIPOTENSION", "PRE HTA", "SIN DATO"],
    "ADHERENCIA AL TRATAMIENTO FARMACOLOGICO (TEST DE MORISKY GREEN)": SI_NO_SD,
    "NOVEDADES": ["FALLECIDO", "NUEVO", "RETIRADO", "ACTIVO", "SIN DATO"],
}

def allowed_for(field_name: str):
    return ALLOWED_BY_NAME.get(field_name, SI_NO)

def field(name: str, type_: str, required: bool = True, allowed: list[str] | None = None):
    return {"name": name.strip(), "type": type_, "required": required, "allowed": allowed or []}

def build_rcv_template():
    template = []
    seen: dict[str, int] = {}

    for base_name, field_type in RAW_FIELDS:
        base = base_name.strip().upper()
        count = seen.get(base, 0) + 1
        seen[base] = count
        unique_name = base if count == 1 else f"{base}_{count}"

        allowed = None
        if field_type == "SET":
            allowed = allowed_for(base)

        template.append(field(unique_name, field_type, True, allowed))

    return template

def get_rcv_template():
    return build_rcv_template()
